apiVersion: v1
kind: Service
metadata:
  name: citadella-game-service
  labels:
    app: citadella-game
spec:
  type: ClusterIP
  selector:
    app: citadella-game
  ports:
    - name: http
      port: 8106
      targetPort: http
